repos = [
  { repo = "local", hooks = [

    {
      id = "ruff-fix",
      name = "Ruff auto-fix",
      entry = "uv run ruff check . --fix",
      language = "system",
      pass_filenames = false,
      stages = ["pre-commit"]
    },

    {
      id = "ruff-format",
      name = "Ruff format",
      entry = "uv run ruff format .",
      language = "system",
      pass_filenames = false,
      stages = ["pre-commit"]
    },

    {
      id = "requirements",
      name = "Generate requirements.txt",
      entry = "uv pip compile pyproject.toml -o requirements.txt",
      language = "system",
      pass_filenames = false,
      files = "pyproject.toml",
      stages = ["pre-commit"]
    },

    {
      id = "clear cache",
      name = "Clearing Prek cache",
      entry = "uv run prek cache clean",
      language = "system",
      pass_filenames = false,
      stages = ["pre-commit"],
    },

    {
      id = "tests",
      name = "Run tests",
      entry = "uv run pytest --cache-clear -vv",
      language = "system",
      pass_filenames = false,
      stages = ["pre-commit"]
    }

  ]}
]
